export * from "./LoginPage/LoginPage.tsx";
export * from "./SignUpPage/SignUpPage.tsx";
export * from "./PatientDetailPage/PatientDetailPage.tsx";
export * from "./ActivateAccountPage/ActivateAccountPage.tsx";
export * from "./ResetPassword/ResetPasswordPage.tsx";
export * from "./ForbiddenPage.tsx";
export * from "./LoginPage/GoogleAuthCallback.tsx";
export * from "./SettingsPage/SettingsPage.tsx";
export * from "./dashboards";
