export enum ErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  OFFICE_NOT_FOUND = "OFFICE_NOT_FOUND",
  APPOINTMENT_NOT_FOUND = "APPOINTMENT_NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND",
}

export interface ApiError {
  errorCode: ErrorCode;
  message: string;
}
