export const ROUTER_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  RESET_PASSWORD: "/reset-password",
  ACTIVATE_EMAIL: "/activate",
  PATIENTS: "/patients",
  PATIENT_DETAIL: "/patients/:id",
  PATIENT_DETAIL_ID: (id: string) => `/patients/${id}`,
  FORBIDDEN: "/forbidden",
  SETTINGS: "/settings",
  OFFICES: "/offices",
  OFFICE_NEW: "/offices/new",
  OFFICE_DETAIL: "/offices/:id",
  OFFICE_DETAIL_ID: (id: string) => `/offices/${id}`,
  OFFICE_APPOINTMENTS: "/offices/:id/appointments",
  OFFICE_APPOINTMENTS_ID: (id: string) => `/offices/${id}/appointments`,
  APPOINTMENTS: "/appointments",
  GOOGLE_AUTH_CALLBACK: "/auth/google/callback",
} as const;
